#!/usr/bin/env bash
set -euo pipefail

shopt -s nullglob

# ============================================================
# run_all.sh
#
# Runs the official CPU regression tests and stores regression
# outputs in combined files only.
#
# Usage:
#   ./run_all.sh
#
# Expected location:
#   sim/run_all.sh
#
# Requirements:
#   - sim/run.sh exists and is executable
#   - sim/run.sh accepts an assembly program path as argument 1
#   - each checked simulation writes summary.log containing:
#       Result : PASS
#
# Combined output files generated by this script:
#   - regression.log
#   - summary_all.log
#   - trace_all.log
#   - instruction_trace_all.log
#   - program_all.hex
#   - sim_output_all.txt, if run.sh creates sim_output.txt
#
# Important behavior:
#   - During each test, run.sh may temporarily create summary.log,
#     trace.log, instruction_trace.log, program.hex, and sim_output.txt.
#   - run_all.sh immediately appends those outputs into combined files.
#   - At the end, run_all.sh removes the individual per-run output files.
#   - Individual output files remain only when run.sh is run directly.
# ============================================================

TESTS=(
    ../programs/*_test.s
)

if [ ${TESTS[@]} -eq 0 ]; then
    echo "FAIL: No test programs found matching ../programs/*_test.s"
    exit 1
fi

REGRESSION_LOG="regression.log"
COMBINED_SUMMARY="summary_all.log"
COMBINED_TRACE="trace_all.log"
COMBINED_INSTRUCTION_TRACE="instruction_trace_all.log"
COMBINED_PROGRAM_HEX="program_all.hex"
COMBINED_SIM_OUTPUT="sim_output_all.txt"

PASS_COUNT=0
TOTAL_COUNT=${#TESTS[@]}

# Individual output files created by run.sh.
RUN_OUTPUTS=(
    "summary.log"
    "trace.log"
    "instruction_trace.log"
    "program.hex"
    "sim_output.txt"
)

# Start fresh regression outputs.
rm -f "$REGRESSION_LOG"
rm -f "$COMBINED_SUMMARY"
rm -f "$COMBINED_TRACE"
rm -f "$COMBINED_INSTRUCTION_TRACE"
rm -f "$COMBINED_PROGRAM_HEX"
rm -f "$COMBINED_SIM_OUTPUT"

# Remove stale individual outputs before starting.
for OUT in "${RUN_OUTPUTS[@]}"; do
    rm -f "$OUT"
done

log() {
    echo "$@" | tee -a "$REGRESSION_LOG"
}

append_section_header() {
    local OUT_FILE="$1"
    local TEST_NAME="$2"
    local PROGRAM_PATH="$3"

    {
        echo ""
        echo "============================================================"
        echo "TEST: $TEST_NAME"
        echo "PROGRAM: $PROGRAM_PATH"
        echo "============================================================"
        echo ""
    } >> "$OUT_FILE"
}

append_required_output() {
    local SRC_FILE="$1"
    local DEST_FILE="$2"
    local TEST_NAME="$3"
    local PROGRAM_PATH="$4"

    if [ ! -f "$SRC_FILE" ]; then
        log "FAIL: $SRC_FILE was not created for $TEST_NAME"
        exit 1
    fi

    append_section_header "$DEST_FILE" "$TEST_NAME" "$PROGRAM_PATH"
    cat "$SRC_FILE" >> "$DEST_FILE"
    echo "" >> "$DEST_FILE"
}

append_optional_output() {
    local SRC_FILE="$1"
    local DEST_FILE="$2"
    local TEST_NAME="$3"
    local PROGRAM_PATH="$4"

    if [ -f "$SRC_FILE" ]; then
        append_section_header "$DEST_FILE" "$TEST_NAME" "$PROGRAM_PATH"
        cat "$SRC_FILE" >> "$DEST_FILE"
        echo "" >> "$DEST_FILE"
    fi
}

log "============================================================"
log "CPU Regression Test Suite"
log "============================================================"
log "Total tests: $TOTAL_COUNT"
log "Combined summary          : $COMBINED_SUMMARY"
log "Combined trace            : $COMBINED_TRACE"
log "Combined instruction trace: $COMBINED_INSTRUCTION_TRACE"
log "Combined program hex      : $COMBINED_PROGRAM_HEX"
log "Combined sim output       : $COMBINED_SIM_OUTPUT, if generated"
log ""

# Basic run.sh sanity check.
if [ ! -f "./run.sh" ]; then
    log "FAIL: ./run.sh not found. Run this script from the sim/ directory."
    exit 1
fi

if [ ! -x "./run.sh" ]; then
    log "INFO: ./run.sh is not executable. Running chmod +x ./run.sh"
    chmod +x ./run.sh
fi

for TEST in "${TESTS[@]}"; do
    TEST_NAME=$(basename "$TEST" .s)

    log "------------------------------------------------------------"
    log "Running test: $TEST_NAME"
    log "Program     : $TEST"
    log "------------------------------------------------------------"

    if [ ! -f "$TEST" ]; then
        log "FAIL: Test program not found: $TEST"
        exit 1
    fi

    # Remove individual outputs from any previous test before this test runs.
    for OUT in "${RUN_OUTPUTS[@]}"; do
        rm -f "$OUT"
    done

    # Run the individual test. pipefail ensures a failing simulation fails
    # the whole regression even though output is piped through tee.
    ./run.sh "$TEST" 2>&1 | tee -a "$REGRESSION_LOG"

    if [ ! -f "summary.log" ]; then
        log "FAIL: summary.log was not created for $TEST_NAME"
        exit 1
    fi

    # Require the automatic checker to explicitly report PASS.
    # This prevents NOT CHECKED tests from being counted as passes.
    if grep -Eq "Result[[:space:]]*:[[:space:]]*PASS" summary.log; then
        log "PASS: $TEST_NAME"
        PASS_COUNT=$((PASS_COUNT + 1))
    else
        log "FAIL: $TEST_NAME did not report PASS in summary.log"
        log "Check summary.log and the terminal output above for details."
        exit 1
    fi

    # Append all outputs to combined files.
    append_required_output "summary.log" "$COMBINED_SUMMARY" "$TEST_NAME" "$TEST"
    append_required_output "trace.log" "$COMBINED_TRACE" "$TEST_NAME" "$TEST"
    append_required_output "instruction_trace.log" "$COMBINED_INSTRUCTION_TRACE" "$TEST_NAME" "$TEST"
    append_required_output "program.hex" "$COMBINED_PROGRAM_HEX" "$TEST_NAME" "$TEST"

    # sim_output.txt is optional because run.sh may or may not create it.
    append_optional_output "sim_output.txt" "$COMBINED_SIM_OUTPUT" "$TEST_NAME" "$TEST"

    # Remove individual outputs so run_all.sh leaves only combined files.
    for OUT in "${RUN_OUTPUTS[@]}"; do
        rm -f "$OUT"
    done

    log "Appended outputs for $TEST_NAME into combined regression files."
    log ""
done

log "============================================================"
log "ALL TESTS PASSED"
log "Passed $PASS_COUNT / $TOTAL_COUNT tests"
log "============================================================"
log "Combined outputs generated:"
log "  $COMBINED_SUMMARY"
log "  $COMBINED_TRACE"
log "  $COMBINED_INSTRUCTION_TRACE"
log "  $COMBINED_PROGRAM_HEX"
if [ -f "$COMBINED_SIM_OUTPUT" ]; then
    log "  $COMBINED_SIM_OUTPUT"
fi
log "  $REGRESSION_LOG"
log "============================================================"