// tb_trap_halt.sv
//
// Dedicated regression test for the sticky trap-halt behaviour.
//
// The main testbench (tb_cpu.sv) calls $finish the moment trap_valid first
// asserts, so it structurally cannot observe what the core does in the cycles
// *after* a trap. That is exactly the window where the original bug lived: the
// PC-freeze and pipeline flushes were gated on the one-cycle combinational
// trap_valid, so the core resumed executing the cycle after it dropped and
// instructions younger than the faulting one committed their writes.
//
// This testbench runs well past the trap and asserts the invariants that the
// sticky-halt fix must uphold:
//   1. Once trapped, the PC never advances again.
//   2. Once trapped, no register write ever commits again.
//   3. trap_valid stays asserted while halted (not a one-cycle pulse), and
//      the reported cause/PC stay stable.
//   4. No register younger than the faulting instruction is ever written.
//
// The program (loaded from program.hex, generated by the runner) is:
//   addi x1, x0, 5      ; ordinary, commits before the trap
//   ecall               ; raises ECALL trap (cause 11)
//   addi x10, x0, 111   ; all four of these are younger than the trap and
//   addi x11, x0, 222   ; must NEVER commit
//   addi x12, x0, 333
//   addi x13, x0, 444
//   halt
 
`timescale 1ns/1ps
module tb_trap_halt;
 
logic clk = 0;
logic reset;
logic trap_valid;
logic [3:0] trap_cause;
logic [31:0] trap_pc;
 
cpu_top uut (
    .clk(clk),
    .reset(reset),
    .trap_valid(trap_valid),
    .trap_cause(trap_cause),
    .trap_pc(trap_pc)
);
 
always #5 clk = ~clk;
 
// Tracking state
logic        seen_trap;
logic [31:0] pc_at_trap;
logic [3:0]  cause_at_trap;
int          errors;
int          cycles_after_trap;
 
initial begin
    seen_trap         = 0;
    errors            = 0;
    cycles_after_trap = 0;
 
    reset = 1;
    repeat (2) @(posedge clk);
    reset = 0;
 
    // Run long enough to (a) reach the trap and (b) watch many cycles beyond it.
    repeat (40) begin
        @(posedge clk);
        #1; // settle
 
        if (trap_valid && !seen_trap) begin
            // First cycle of the trap: latch what we expect to stay frozen.
            seen_trap     = 1;
            pc_at_trap    = uut.pc;
            cause_at_trap = trap_cause;
 
            if (trap_cause != 4'd11) begin
                $display("FAIL: expected ECALL cause 11, got %0d", trap_cause);
                errors++;
            end
        end
        else if (seen_trap) begin
            cycles_after_trap++;
 
            // 1. PC must not have moved.
            if (uut.pc !== pc_at_trap) begin
                $display("FAIL: PC moved after trap (0x%08h -> 0x%08h)",
                         pc_at_trap, uut.pc);
                errors++;
            end
 
            // 3. Trap must stay asserted and stable while halted.
            if (!trap_valid) begin
                $display("FAIL: trap_valid dropped %0d cycles after trap",
                         cycles_after_trap);
                errors++;
            end
            if (trap_cause !== cause_at_trap) begin
                $display("FAIL: trap_cause changed after trap (%0d -> %0d)",
                         cause_at_trap, trap_cause);
                errors++;
            end
        end
    end
 
    // 4. Final architectural state: no younger instruction committed.
    if (uut.rf.regs[10] !== 32'd0) begin
        $display("FAIL: x10 = %0d (younger instruction committed after trap)",
                 uut.rf.regs[10]); errors++;
    end
    if (uut.rf.regs[11] !== 32'd0) begin
        $display("FAIL: x11 = %0d (younger instruction committed after trap)",
                 uut.rf.regs[11]); errors++;
    end
    if (uut.rf.regs[12] !== 32'd0) begin
        $display("FAIL: x12 = %0d (younger instruction committed after trap)",
                 uut.rf.regs[12]); errors++;
    end
    if (uut.rf.regs[13] !== 32'd0) begin
        $display("FAIL: x13 = %0d (younger instruction committed after trap)",
                 uut.rf.regs[13]); errors++;
    end
 
    // x1 (older than the trap) SHOULD have committed before the trap.
    if (uut.rf.regs[1] !== 32'd5) begin
        $display("FAIL: x1 = %0d, expected 5 (older instruction should commit)",
                 uut.rf.regs[1]); errors++;
    end
 
    if (!seen_trap) begin
        $display("FAIL: trap was never raised");
        errors++;
    end
 
    $display("\n==================== TRAP-HALT TEST ====================");
    if (errors == 0) begin
        $display("PASS: core halted correctly on trap");
        $display("  - PC parked at 0x%08h", pc_at_trap);
        $display("  - trap_valid held for %0d observed cycles", cycles_after_trap);
        $display("  - no younger instruction (x10-x13) committed");
        $display("  - older instruction (x1) committed normally");
    end
    else begin
        $display("FAIL: %0d halt-behaviour error(s) detected", errors);
    end
    $display("=======================================================\n");
 
    if (errors != 0) $fatal(1, "trap-halt regression failed");
    $finish;
end
 
endmodule
